name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Pull & build in project directory
        run: |
          cd D:\BARANGAYCC\barangay-system
          git pull origin main
          npm ci
          npm run build -- --mode production
          Copy-Item -Path "dist\*" -Destination "pb_public\" -Recurse -Force
          Restart-Service -Name PocketBase -Force
